// src/services/db.service.ts

import { db } from './firebase.service'
import { GameState } from '../models/GameState'
import * as admin from 'firebase-admin'

// Reference to the main collection for game data
const gameCollection = db.collection('games')

/**
 * Service class for CRUD operations on the 'games' collection in Firestore.
 */
export class DBService {
  // The constructor is clean since firebase.service.ts handles initialization
  constructor() {}

  /**
   * Creates a new game document in Firestore.
   * @param gameState The initial GameState object.
   * @returns The ID of the newly created document.
   */
  public async createGame(gameState: GameState): Promise<string> {
    // Use set to ensure the ID from the GameState is used, or add if the ID is generated by Firestore
    // Since GameState includes its own ID, we'll use set()
    const gameId = gameState.id

    await gameCollection.doc(gameId).set({
      ...gameState,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    })

    return gameId
  }

  /**
   * Retrieves the GameState by ID.
   * @param id The game document ID.
   * @returns The GameState or null.
   */
  public async loadGameState(id: string): Promise<GameState | null> {
    const doc = await gameCollection.doc(id).get()
    // We cast to GameState, assuming Firestore data structure matches our interface
    return doc.exists ? (doc.data() as GameState) : null
  }

  /**
   * Updates an existing game document.
   * @param id The game document ID.
   * @param data Partial GameState data to update.
   */
  public async saveGameState(gameState: GameState): Promise<void> {
    // We use the ID already on the object to update the document
    const id = gameState.id
    await gameCollection.doc(id).update({
      ...gameState,
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    })
  }

  // You can keep the delete method if needed, but it's not strictly required by the GDD
  public async deleteGame(id: string): Promise<void> {
    await gameCollection.doc(id).delete()
  }
}
