// models/agent-schemas.ts

import { GameDocument, TurnHistoryEntry } from './db-schemas'

// --- 2.1. LLM Outcome Templates ---

/**
 * The final structure of resource/meter/map changes applied by the Agent.
 * This is nested inside the ChoiceModel.
 */
export interface OutcomeTemplate {
  narrative: string
  resource_changes: Record<string, number> // Changes to D, Hw, PC, ES
  meter_changes: Record<string, number> // Changes to human_panic, ai_infiltration
  map_updates: Record<string, string> // Status changes: { 'usa': 'assimilated' }
}

/**
 * Defines a single choice option and its consequences, as generated by the LLM.
 */
export interface ChoiceModel {
  key: string // e.g., 'A', 'B', 'C'
  description: string
  outcome_template: OutcomeTemplate
}

/**
 * The rigid, final JSON structure the LLM MUST return for every turn.
 */
export interface LLMOutputResponse {
  news_event: string
  choices: ChoiceModel[]
}

// --- 2.2. Agent Input/Context ---

/**
 * The model for the input context prepared by the Agent
 * before being sent to the LLM.
 */
export interface TurnInputContext {
  mode: 'Singularity' | 'Anthropocene'
  current_turn: number

  // A snapshot of all current state values
  current_state: {
    resources: Record<string, number>
    meters: Record<string, number>
    map_status: Record<string, string>
  }

  // Summary generated from the event_log to keep the prompt small
  recent_history_summary: string

  // The user's choice (passed from the API route)
  player_choice_key: string
}

// --- 2.3. Agent's Calculated Output ---

/**
 * The final structure of the updated game state calculated by the Agent
 * after processing the LLM output and applying the chosen outcome.
 * This is what is written to the DB and sent to the frontend.
 */
export interface UpdatedGameState {
  updated_game_doc: GameDocument
  chosen_outcome_entry: TurnHistoryEntry // The entry that was just added to the log
  // Optional: any specific message to the frontend, like a 'Victory' banner
  message?: string
}
