import { GameEvent } from './Event'
import { GameState } from './GameState'

/**
 * Defines the structure for a narrative response generated by the LLM service.
 */
export interface LLMResponse {
  /** The generated narrative text */
  narrative: string
  /** Optional: A tone or style tag (e.g., 'Satirical', 'Dark', 'Technical') */
  tone?: string
}

/**
 * Defines the payload sent to the LLM service to request a narrative update.
 */
export interface LLMRequestPayload {
  /** The current state of the game */
  gameState: Partial<GameState>
  /** The specific event that just occurred */
  event: GameEvent
  /** A prompt or context to guide the LLM's response */
  promptContext: string
}
