/**
 * @file LLMSchemas.ts
 * @description Defines the structures exchanged between backend logic and the LLM service.
 */

/**
 * Represents a single action option generated by the LLM.
 */
export interface LLMActionOption {
  /** Short label shown to the player */
  label: string
  /** Narrative text or headline describing the action */
  headline: string
  /** Optional flavor or context text */
  description?: string
  /** Underlying mechanical effect identifier (e.g., "reduce_stability") */
  effectType: string
  /** Predefined Power cost of the action */
  powerCost: number
  /** Predefined Control delta applied when executed */
  deltaControl: number
  /** Predefined Stability delta applied when executed */
  deltaStability: number
}

/**
 * Represents the entire set of options for a single turn.
 */
export interface LLMActionHand {
  /** Associated game ID for which these actions were generated */
  gameId: string
  /** The region targeted by this hand */
  targetRegion: string
  /** List of candidate actions for the player to choose from */
  options: LLMActionOption[]
}

/**
 * Represents the narrative result returned after executing an action.
 */
export interface LLMActionResult {
  /** Headline or title returned by the LLM */
  headline: string
  /** Narrative paragraph describing the outcome */
  narrative: string
  /** Optional flavor quote or aftermath note */
  aftermath?: string
  /** Optional modifier data if needed (awareness spike, chain reaction, etc.) */
  modifiers?: Record<string, number>
}
